# Generated by Django 3.2.25 on 2024-03-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20240324_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=250),
        ),
    ]
