# Generated by Django 3.2.25 on 2024-03-25 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
